title: "#define ❤︎"
description:
  Ramblings. Mostly about digital products, but sometimes
  about actual useful stuff.

permalink: /posts/:title
url: "http://arrelid.com"

sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-redirect-from # Ingenious redirects - https://github.com/jekyll/jekyll-redirect-from

redirect_from:
  json: false # Released in version 0.16.0, GH Pages uses 0.15.0... oh well, keeping it for now

source: site-src
destination: site-build
