url: "http://arrelid.com"

title: "#define ❤︎"
author: Mattias Arrelid
description: >-
  Ramblings. Mostly about digital products, but sometimes
  about actual useful stuff.

twitter_username: arrelid
github_username:  arrelid

permalink: /posts/:title

header_pages:
  - about.md

theme: minima

plugins:
  - jekyll-feed
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - gems/
